### ISSUE TITLE
Shell: make arrow keys move the cursor

### ISSUE THREAD

**Issue by adiee5** [cnelson20/cx16os#3]
When pressing right and left, cursor does not move. Adding the ability to move cursor would make editing more convenient. 

tip: you could try injecting *$94* before feeding a letter to kernal print routine if you want to mimic the behavior of modern terminals

**Comment by cnelson20** [comment]
The latest commit lets the user cursor around in the shell. I will make a new release so you can try it out soon. Going to mark this as closed for now
